build:
  environment:
    php: 8.3

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run

checks:
  php:
    code_rating: true
    duplication: true

tools:
  external_code_coverage:
    timeout: 900
    runs: 1

filter:
  paths:
    - src/*
  excluded_paths:
    - tests/*
    - vendor/*
